### ISSUE TITLE
[FEAT] 데이터베이스 엔티티 연관 관계 매핑 설정

### ISSUE THREAD

**Issue by howudong** [Spharos-MSG/backend#10]
**기능 설명**
JPA를 통해 연관관계 매핑을 진행합니다.
연관관계는 모두 작성은 ERD에 근거합니다.
![슈뢰딩거의 ERD](https://github.com/Spharos-MSG/backend/assets/53307093/5665c210-55a3-4115-8715-e87b84e6c867)

- [x] PRODUCT : 
  - [x] PRODUCT : PRODUCT_OPTION(1:N)
  - [x] PRODUCT : PRODUCT_SALES_INFO(1 :1)
  - [x] PRODUCT : DELIVERY_FEE_INFO(1:N)
  - [x] PRODUCT : VENDER(N:1)
  - [x] PRODUCT : PRODUCT_INFO_DETAIL(1:N)
  - [x] PRODUCT : PRODUCT_IMAGE(1:N)
  - [x] PRODUCT : LIKES(1:N)
  - [x] PRODUCT : CATEGORY_PRODUCT(1:N)
  - [x] PRODUCT : BUNDLE_PRODUCT(1:N)

- [x] BUNDLE
  - [x] BUNDLE : BUNDLE_PRODUCT(1:N)

- [x] PRODUCT_OPTION
  - [x] PRODUCT_OPTION : PRODUCT(N:1)
  - [x] PRODUCT_OPTION :OPTION_SIZE(N:1)
  - [x] PRODUCT_OPTION : OPTION_COLOR(N:1)
  - [x] PRODUCT_OPTION : OPTION_ETC(N:1)
  - [x] PRODUCT_OPTION : CART_PRODUCT(1:N)

- [x] KAKAO_USER
- [x] USERS
  - [x] USERS : CART_PRODUCT (1:N)
  - [x] USERS: USER_COUPON(1:N)
  - [x] USERS : LIKE(1:N)

- [x] COUPON
  - [x] COUPON : USER_COUPON(1:N)

- [x] CATEGORY
  - [x] CATEGORY : CATEGORY (1:N)
  - [x] CATEGORY : CATEGORY_PRODUCT (1:N)

- [x] PAYMENT : ORDERS(1:N)
- [x] ORDERS : ORDER_DETAIL(1:N)
- [x] ORDER_DETAIL : REVIEW(1:N)
- [x] REVIEW : REVIEW_IMAGE(1:N)

**Comment by YOON-CC** [comment]
백 멋지다...
