### ISSUE TITLE
[WANT] JwtTokenProvider 토큰 검증 로직에 대한 수정 요청

### ISSUE THREAD

**Issue by howudong** [Spharos-MSG/backend#53]
## 요청하는 편집의 종류
JwtTokenProvider 메서드 수정

## 요청하는 편집에 대한 상세 설명
token을 받아온 뒤 JwtTokenProvider를 통해 validate 및 uuid를 받아옵니다.
이 과정에서 validateAndGetUserUuid 메서드를 사용하면, 에러가 발생하는데 그 원인을 발생했습니다.

원인은 해당 메서드 사용 과정에서 문자열에서 "Bearer "를 제외하는 과정이 포함되어 있지 않습니다.
그래서 validateAndGetUserUuid 메소드에 이 과정을 추가하길 요청드립니다. 

## 기대하는 결과
```java
    @Operation(summary = "주문자 정보 조회", description = "토큰을 통해 주문자의 정보를 조회합니다.")
    @GetMapping("/user")
    public ApiResponse<?> orderUserAPI(
        @Parameter(hidden = true)
        @RequestHeader(AUTHORIZATION) String token) {

        String uuid = jwtTokenProvider.validateAndGetUserUuid(token); // 여기서 예외가 발생하지 않는것
        OrderUserDto orderUserDto = orderService.findOrderUser(uuid);
        return ApiResponse.of(SuccessStatus.ORDER_USER_SUCCESS, orderUserDto);
    }
```

**Comment by KangBaekGwa** [comment]
해당 메소드는 security 내부에서 사용하게 설계되어있어, 문제점이 발생한 것 같습니다.

따라서, 추가적인 메소드를 구현하여 배포하도록 하겠습니다!

예상 메소드명) getUuid(String token)
